import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import crypto from 'crypto';
import { ethers } from 'ethers';
import KeyRotationService from '../../../src/services/security/keyRotationService.js';

const mocks = vi.hoisted(() => ({
  supabaseInsert: vi.fn(),
  insertCalls: [],
}));

vi.mock('@sentry/node', () => ({
  captureException: vi.fn(),
}));

vi.mock('../../../src/config/db.js', () => {
  const from = vi.fn((table) => ({
    insert: vi.fn((rows) => {
      mocks.insertCalls.push({ table, rows });
      return {
        select: vi.fn(() => ({
          single: mocks.supabaseInsert,
        })),
      };
    }),
    select: vi.fn(() => ({
      eq: vi.fn(() => ({
        eq: vi.fn(() => ({
          order: vi.fn(() => ({
            limit: vi.fn().mockResolvedValue({ data: [], error: null })
          }))
        }))
      }))
    })),
    update: vi.fn(() => ({
      eq: vi.fn().mockResolvedValue({ error: null })
    }))
  }));
  return {
    default: { supabase: { from } },
    supabase: { from },
  };
});

vi.mock('../../../src/middleware/logger.js', () => ({
  default: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

describe('KeyRotationService', () => {
  let service;

  const OLD_PRIVATE_KEY = '0x' + 'a'.repeat(64);
  const NEW_PRIVATE_KEY = '0x' + 'b'.repeat(64);
  const OLD_ADDRESS = new ethers.Wallet(OLD_PRIVATE_KEY).address;
  const NEW_ADDRESS = new ethers.Wallet(NEW_PRIVATE_KEY).address;
  const ESCROW_ADDRESS = '0x0000000000000000000000000000000000000001';
  const TX_HASH = '0x' + 'c'.repeat(64);

  const escrowInterface = new ethers.Interface([
    'function transferKeyOwnership(address newKeyAddress, uint256 nonce) external',
  ]);

  function makeService(overrides = {}) {
    const escrowContract = {
      target: ESCROW_ADDRESS,
      interface: escrowInterface,
    };
    return new KeyRotationService({ escrowContract, ...overrides });
  }

  function mockTransactionSuccess(blockNumber = 123) {
    return vi.spyOn(ethers.Wallet.prototype, 'sendTransaction').mockResolvedValue({
      hash: TX_HASH,
      wait: async () => ({ hash: TX_HASH, blockNumber, status: 1 }),
    });
  }

  beforeEach(() => {
    service = new KeyRotationService({});
    mocks.supabaseInsert.mockClear();
    mocks.insertCalls.length = 0;
    mocks.supabaseInsert.mockResolvedValue({ data: { id: 1 }, error: null });
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('createRotationRecord', () => {
    it('generates a standard UUID-based rotation ID', async () => {
      const rotationId = await service.createRotationRecord('user-1', '0x123', 'routine');

      expect(rotationId).toBeDefined();
      expect(rotationId.startsWith('rot_')).toBe(true);

      const uuidPart = rotationId.replace('rot_', '');

      // Standard UUID format regex (covers v4 generated by crypto.randomUUID)
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      expect(uuidRegex.test(uuidPart)).toBe(true);
    });

    it('generates unique collision-resistant IDs', async () => {
      const rotationId1 = await service.createRotationRecord('user-1', '0x123', 'routine');
      const rotationId2 = await service.createRotationRecord('user-1', '0x123', 'routine');

      expect(rotationId1).not.toBe(rotationId2);
    });
  });

  describe('transferKeyOwnershipOnChain', () => {
    it('derives the new wallet public address from the new private key', () => {
      const derived = new ethers.Wallet(NEW_PRIVATE_KEY).address;

      expect(derived).toBe(NEW_ADDRESS);
      expect(derived).toMatch(/^0x[0-9a-fA-F]{40}$/);
    });

    it('passes only the derived public address to transferKeyOwnership', async () => {
      service = makeService();
      const sendTxSpy = mockTransactionSuccess();

      const result = await service.transferKeyOwnershipOnChain(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
      );

      const sentTx = sendTxSpy.mock.calls[0][0];
      expect(sentTx.to).toBe(ESCROW_ADDRESS);

      const parsed = escrowInterface.parseTransaction({ data: sentTx.data });
      expect(parsed.name).toBe('transferKeyOwnership');
      expect(parsed.args[0]).toBe(NEW_ADDRESS);
      expect(typeof parsed.args[1]).toBe('bigint');

      expect(result).toEqual({ status: 'success', txHash: TX_HASH, blockNumber: 123 });
    });

    it('does NOT pass the raw private key to the contract', async () => {
      service = makeService();
      const sendTxSpy = mockTransactionSuccess();

      await service.transferKeyOwnershipOnChain(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
      );

      const sentTx = sendTxSpy.mock.calls[0][0];
      const parsed = escrowInterface.parseTransaction({ data: sentTx.data });

      expect(parsed.args[0].toLowerCase()).not.toBe(NEW_PRIVATE_KEY.toLowerCase());
      expect(parsed.args[0].toLowerCase()).not.toBe(OLD_PRIVATE_KEY.toLowerCase());
    });

    it('RAW_PRIVATE_KEY NOT IN TRANSACTION_DATA', async () => {
      service = makeService();
      const sendTxSpy = mockTransactionSuccess();

      await service.transferKeyOwnershipOnChain(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
      );

      const calldata = sendTxSpy.mock.calls[0][0].data.toLowerCase();

      expect(calldata).not.toContain(NEW_PRIVATE_KEY.toLowerCase());
      expect(calldata).not.toContain(NEW_PRIVATE_KEY.slice(2).toLowerCase());
      expect(calldata).not.toContain(OLD_PRIVATE_KEY.toLowerCase());
      expect(calldata).not.toContain(OLD_PRIVATE_KEY.slice(2).toLowerCase());
    });

    it('persists only public-address metadata, never private-key fragments', async () => {
      service = makeService();
      mockTransactionSuccess(42);

      await service.transferKeyOwnershipOnChain(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
      );

      const transferInsert = mocks.insertCalls.find((c) => c.table === 'key_ownership_transfers');
      expect(transferInsert).toBeDefined();

      const row = transferInsert.rows[0];
      expect(row.old_wallet_address).toBe(OLD_ADDRESS);
      expect(row.new_wallet_address).toBe(NEW_ADDRESS);
      expect(row.wallet_address).toBe(OLD_ADDRESS);
      expect(row.tx_hash).toBe(TX_HASH);
      expect(row.block_number).toBe(42);
      expect(row.completed_at).toBeDefined();

      expect(row).not.toHaveProperty('old_key');
      expect(row).not.toHaveProperty('new_key');

      const serialized = JSON.stringify(row).toLowerCase();
      expect(serialized).not.toContain(NEW_PRIVATE_KEY.toLowerCase());
      expect(serialized).not.toContain(NEW_PRIVATE_KEY.slice(2).toLowerCase());
      expect(serialized).not.toContain(OLD_PRIVATE_KEY.toLowerCase());
      expect(serialized).not.toContain(OLD_PRIVATE_KEY.slice(2).toLowerCase());
    });

    it('returns skipped when the escrow contract is not configured', async () => {
      service = new KeyRotationService({});

      const result = await service.transferKeyOwnershipOnChain(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
      );

      expect(result).toEqual({ status: 'skipped', reason: 'contract_unavailable' });
    });

    it('rejects invalid private keys without sending a transaction', async () => {
      service = makeService();
      const sendTxSpy = vi.spyOn(ethers.Wallet.prototype, 'sendTransaction');

      await expect(
        service.transferKeyOwnershipOnChain('user-1', OLD_ADDRESS, 'not-a-private-key', NEW_PRIVATE_KEY)
      ).rejects.toThrow('Invalid private key format');

      await expect(
        service.transferKeyOwnershipOnChain('user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, '0x1234')
      ).rejects.toThrow('Invalid private key format');

      expect(sendTxSpy).not.toHaveBeenCalled();
    });

    it('rejects a private key that cannot derive a wallet address', async () => {
      service = makeService();
      // 0xffff…ff is outside the secp256k1 curve order, so ethers cannot
      // construct a wallet from it even though it is 64 hex characters.
      const outOfRangeKey = '0x' + 'f'.repeat(64);

      await expect(
        service.transferKeyOwnershipOnChain('user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, outOfRangeKey)
      ).rejects.toThrow();
    });

    it('propagates blockchain transaction failures', async () => {
      service = makeService();
      vi.spyOn(ethers.Wallet.prototype, 'sendTransaction').mockRejectedValue(new Error('RPC timeout'));

      await expect(
        service.transferKeyOwnershipOnChain('user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY)
      ).rejects.toThrow('On-chain key ownership transfer failed: RPC timeout');
    });

    it('redacts private-key material from error messages', async () => {
      service = makeService();
      vi.spyOn(ethers.Wallet.prototype, 'sendTransaction').mockRejectedValue(
        new Error('signing failed near ' + NEW_PRIVATE_KEY + ' and ' + OLD_PRIVATE_KEY + ' end')
      );

      await expect(
        service.transferKeyOwnershipOnChain('user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY)
      ).rejects.toThrow(
        'On-chain key ownership transfer failed: signing failed near [REDACTED] and [REDACTED] end'
      );
    });

    it('does not fail the rotation when the best-effort receipt write fails', async () => {
      service = makeService();
      mockTransactionSuccess(7);

      // Force the audit insert to fail by making the chained insert throw.
      const errorInsert = new Error('relation does not exist');
      const origPush = mocks.insertCalls.push;
      mocks.insertCalls.push = () => { throw errorInsert; };

      try {
        const result = await service.transferKeyOwnershipOnChain(
          'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY
        );

        expect(result).toEqual({ status: 'success', txHash: TX_HASH, blockNumber: 7 });
      } finally {
        mocks.insertCalls.push = origPush;
      }
    });
  });

  describe('initiateKeyRotation', () => {
    function makeKeyManagementService() {
      return {
        validatePrivateKey: vi.fn(() => true),
        retrieveEncryptedKey: vi.fn(async () => ({ key_id: 'key-current' })),
        archiveKey: vi.fn(async () => true),
        generateMasterSecret: vi.fn(() => 'masters3cret'),
        encryptPrivateKey: vi.fn(async () => ({
          iv: 'iv', encryptedKey: 'enc', authTag: 'tag', salt: 'salt', algorithm: 'aes-256-gcm',
        })),
        storeEncryptedKey: vi.fn(async () => 'new-key-id'),
      };
    }

    it('completes the existing rotation workflow successfully', async () => {
      const keyManagementService = makeKeyManagementService();
      service = makeService({ keyManagementService });

      const result = await service.initiateKeyRotation(
        'user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY, 'routine'
      );

      expect(result).toEqual({
        rotationId: expect.stringMatching(/^rot_/),
        status: 'success',
        message: 'Key rotated successfully',
      });
      expect(keyManagementService.archiveKey).toHaveBeenCalledWith('key-current', 'rotation_reason_routine');
      expect(keyManagementService.storeEncryptedKey).toHaveBeenCalled();
    });

    it('fails cleanly on invalid private keys and releases the rotation lock', async () => {
      const keyManagementService = makeKeyManagementService();
      keyManagementService.validatePrivateKey.mockReturnValue(false);
      service = makeService({ keyManagementService });

      await expect(
        service.initiateKeyRotation('user-1', OLD_ADDRESS, OLD_PRIVATE_KEY, NEW_PRIVATE_KEY, 'routine')
      ).rejects.toThrow('Invalid private key format');

      expect(service.rotationLocks.has('user-1:' + OLD_ADDRESS)).toBe(false);
    });
  });
});
